kubernetes/heapster

- heapster.go
Vet says 'remove unreachable code'. Hopefully also tests the travis script :)
> Fix vet error.

- .travis.yml
Just realized that cAdvisor wasn't checking vet for all dirs. Same applies here too.
> Add vet checks for all subdirectories.

- .travis.yml
- clusters/coreos/buddy.go
- sources/cadvisor.go
> Update .travis to use vet from its new package location.

- clusters/coreos/buddy.go
Added a flag to change the default or add new fleet servers #11
>  Added flag to add fleet servers

- influx-grafana/grafana/set_basic_auth.sh
Fixes a bug pointed out by @antmanler.
> Updating bug in Grafana setup scripts.

- integration/framework.go
- integration/kube_test.go
The intent is to run this periodically (nightly maybe).
> Adding an integration test

- integration/framework.go
- integration/kube_test.go
also fixed bugs in integration test.
> Add firewall rules for integration testing.

- deploy/influxdb-grafana-controller.yaml
- deploy/kube.sh
- influx-grafana/influxdb/Dockerfile
- influx-grafana/influxdb/RELEASES.md
- influx-grafana/influxdb/build.sh
- influx-grafana/influxdb/collectd-types.db
- influx-grafana/influxdb/config.toml
Bumped up influx container version number.
This update paves way for adding collectd support in influxdb.
> Updating influxdb version to 0.8.8. 

- deploy/grafana-service.yaml
- deploy/heapster-controller.yaml
- deploy/influxdb-service.yaml
- deploy/kube.sh
- deploy/run.sh
- integration/kube_test.go
Environment variables based service discovery is still the first choice.
Updated service config to use port 80 since kube dns seems to require that.
Fixed initialization errors in kube source.
> Make heapster discover InfluxDB service using DNS.

- deploy/heapster-controller.yaml
- influx-grafana/grafana/kubernetes-dashboard.json
- influx-grafana/grafana/run.sh
Update default dashboard to use labels instead of pod names.
> Fix heapster controller spec.

- RELEASES.md
- deploy/heapster-controller.yaml
- deploy/heapster-service.yaml
- deploy/influxdb-grafana-controller.yaml
- sources/kube.go
- version/version.go
Added a service for heapster to access the '/validate' endpoint.
> Release heapster v0.6

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go
- Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go
- sinks/gcm/auth.go
- sinks/gcm/gcm_driver.go
- sinks/gcm/sink.go
Driver performs the authentication and interaction with the GCM	API. The
sink will perform the actual creation and formatting of metrics.
> Adding GCM driver for the GCM sink.

- sinks/gcm/metrics.go
- sinks/gcm/sink.go
> Moving metrics to their own file.

- sinks/gcm/metrics.go
- sinks/gcm/sink.go
- sinks/influxdb.go
The stats are handled incorrectly.
#95
> Remove diskio stats from being pushed to InfluxDB. 

- sinks/influxdb.go
.. to avoid superficial warning.
> Create InfluxDB database only if not exist

- heapster.go
- sources/cadvisor.go
- sources/external.go
- sources/kube.go
- sources/types.go
> Fix housekeeping stats collection

- README.md
- deploy/build-test.sh
- deploy/influxdb-grafana-controller.yaml
- influx-grafana/grafana/RELEASES.md
- influx-grafana/grafana/build-test.sh
- influx-grafana/grafana/run.sh
- influx-grafana/influxdb/build-test.sh
- integration/framework.go
- integration/kube_test.go
> Grafana v0.4 with proxy service support

- README.md
- deploy/influxdb-ui-service.yaml
- deploy/kube.sh
Fixed Readme and the kube.sh script.
> Add influxdb-ui service

- README.md
Not an overhaul or change of structure; mostly capitalization and indenting fixes, with a little tweaks for clarification
Preview at:
https://github.com/mbforbes/heapster/blob/readme/README.md
> Cleanup README.

- RELEASES.md
- clusters/coreos/README.md
- deploy/Dockerfile
- deploy/build.sh
- deploy/run.sh
- sources/cadvisor.go
- sources/cadvisor_test.go
- sources/kube.go
- sources/kube_test.go
- sources/nodes/coreos.go
- sources/nodes/coreos_test.go
- sources/nodes/external.go
- sources/nodes/external_test.go
- sources/nodes/kube.go
- sources/test_utils.go
- sources/types.go
> Native support for CoreOS.

- deploy/heapster-controller.yaml
> Add host volume with TLS certs.

- sources/pods.go
More logs added after a recent debugging session.
> Improve logging in pods aggregation.

- deploy/grafana-service.yaml
- deploy/heapster-controller.yaml
- deploy/heapster-service.yaml
- deploy/influxdb-grafana-controller.yaml
- deploy/influxdb-service.yaml
- deploy/influxdb-ui-service.yaml
- deploy/v1beta3/grafana-service.yaml
- deploy/v1beta3/heapster-controller.yaml
- deploy/v1beta3/heapster-service.yaml
- deploy/v1beta3/influxdb-grafana-controller.yaml
- deploy/v1beta3/influxdb-service.yaml
- deploy/v1beta3/influxdb-ui-service.yaml
> change json files to support v1beta3

- integration/.jenkins.sh
Do not merge this PR until I confirm that the script works as intended.
> Fix exit code issue in integration test script. Attempt 2.

- sinks/api/decoder.go
- sinks/api/decoder_test.go
- sinks/api/supported_labels.go
- sinks/api/supported_metrics.go
- sinks/api/types.go
- sinks/gcm.go
- sources/api/types.go
- sources/pods.go
> Created a unified external sinks api based off the existing gcm infrastructure.

- Godeps/_workspace/src/github.com/google/gofuzz/CONTRIBUTING.md
- Godeps/_workspace/src/github.com/google/gofuzz/LICENSE
- Godeps/_workspace/src/github.com/google/gofuzz/README.md
- Godeps/_workspace/src/github.com/google/gofuzz/doc.go
- Godeps/_workspace/src/github.com/google/gofuzz/example_test.go
- Godeps/_workspace/src/github.com/google/gofuzz/fuzz.go
- Godeps/_workspace/src/github.com/google/gofuzz/fuzz_test.go
- sinks/api/decoder_test.go
Looks like I had update Godeps.json but failed to add the actual dependencies.
cc @vmarmol
> Add missing gofuzz deps

- deploy/run.sh
It does not work in certain modes without this PR
> Fix heapster startup script.

- deploy/grafana-service.yaml
- deploy/v1beta3/grafana-service.yaml
- deploy/v1beta3/heapster-controller.yaml
- deploy/v1beta3/heapster-service.yaml
- deploy/v1beta3/influxdb-grafana-controller.yaml
@vishh I have updated the yaml files with some of the changes done in kubernetes repo
Kindly review
I have tested these and they work
> Update v1beta3 json files

- deploy/kube-config/grafana-service.yaml
- deploy/kube-config/influxdb-grafana-controller.yaml
- deploy/kube-config/v1beta3/grafana-service.yaml
- deploy/kube-config/v1beta3/heapster-service.yaml
- deploy/kube-config/v1beta3/influxdb-grafana-controller.yaml
- deploy/kube-config/v1beta3/influxdb-service.yaml
- deploy/kube-config/v1beta3/influxdb-ui-service.yaml
Updated the v1beta1 configs to be in sync with v1beta3. May be its time to have a script dynamically generate the configs instead of maintaining one.
> Fix grafana service config. It is currently using an invalid selector.

- sources/datasource/kubelet.go
- sources/kube.go
Improved error handling of kubelet http requests.
Fixes #170
> Making heapster resilient to kubelet failures.

- deploy/docker/run.sh
So that multiple options can be passed in
> Allow flags with spaces

- docs/storage-schema.md
> Adding documentation for current storage schema.

- docs/debugging.md
This is currently a brain dump. Needs polishing.
Fixes #185
> Debugging FAQ

- sinks/api/decoder.go
The lack of label copies was leading to unexpected duplicates.
Fixes #107.
> Copy labels and rount timestamps to seconds.

- deploy/kube-config/grafana-service.yaml
- deploy/kube-config/influxdb-grafana-controller.yaml
- deploy/kube-config/v1beta3/grafana-service.yaml
- deploy/kube-config/v1beta3/influxdb-grafana-controller.yaml
- grafana/Dockerfile
- grafana/config.js.tmpl
> Make the grafana setup work via apiserver proxy.

- sinks/gcm/driver.go
- Round metric timestamps to 1s.
- Only send strictly greater than metrics.
- Don't send more than 200 per request.
- Only one metric of type per request.
Filed #175 for an integration test.
> Apply GCM request policies.

- integration/.jenkins.sh
- integration/framework.go
- integration/kube_test.go
Also updated the integration test to validate that all pods and nodes in the cluster be present in Influxdb
> Update kube version to test against to 0.14.0

- integration/.jenkins.sh
0.14.0 has a scheduler bug that leading to hostport conflicts.
> Revert back to kube release 0.13.2 

- Makefile
- deploy/kube-config/v1beta3/heapster-controller.yaml
- integration/kube_test.go
- sources/kube.go
> Add support to run heapster using Kube v1beta3 API.

- sources/events_fake.go
- sources/kube.go
As of now it will burn compute resources.
cc @saad-ali
> Disable events until a sink is added. 

- .gitignore
> Have git ignore VIM scratch files

- sinks/gcm/driver.go
- util/gcstore/gcstore.go
- util/gcstore/gcstore_test.go
Will followup this PR with one that makes the metrics a little more human friendly. No need to make CPU be in billionths of a core for example :)
> Make cumulative metrics gauge metrics in GCM

- Makefile
- docs/integration.md
- integration/.jenkins.sh
- integration/framework.go
- integration/kube_test.go
- sources.go
- sources/kube_factory.go
updated integration tests to use 0.15.0 release
> Update kubelet port to 10255

- sinks/gcm/driver.go
Makes units more user friendly for some metrics:
- uptime: seconds/second
- CPU usage: millicores/second
> GCM: Export metrics as floats and change units.

- docs/storage-schema.md
- sinks/gcm/driver.go
- sinks/gcm/rate_metrics.go
@vmarmol: If this change works, then I will update the docs before this PR gets merged.
> Add instantaneous metrics in addition to cumulative metrics in GCM driver

- sinks/external.go
- sinks/gcl/driver.go
- sinks/gcl/driver_test.go
- sinks/gcm/driver.go
- util/gce/auth.go
> Add Google Cloud Logging (GCL) sink for events to heapster

- docs/overview.md
> Add Heapster overview documentation

- Makefile
- deploy/docker/run.sh
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/influxdb/v1beta3/heapster-controller.json
- docs/sink-configuration.md
- heapster.go
- modules.go
- sinks.go
- sinks/external.go
- sinks/gcl/driver.go
- sinks/gcm/driver.go
- sinks/influxdb/driver.go
- sinks/influxdb/driver_test.go
- sinks/modules.go
Docs will come soon, either in this PR or in a later PR.
cc @vmarmol @saad-ali @jimmidyson
> Configure multiple sinks

- deploy/kube-config/influxdb/v1beta3/influxdb-grafana-controller.json
> Specify host/container ports for InfluxDB, so that the UI is accessible

- RELEASES.md
- docs/storage-schema.md
- grafana/RELEASES.md
- version/version.go
I will make a github release once this PR is merged.
> Releasing version v0.11.0

- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
A PR to use the auth files will show up soon. 
Also removed kube auth version flag.
> Adding secrets as a volume.

- Makefile
- docs/source-configuration.md
- sources/kube_factory.go
> Make heapster use monitoring secret to connect with kubernetes master securely

- heapster.go
- manager/manager.go
- sinks/api/types.go
- sinks/external.go
- sinks/gcl/driver.go
- sinks/gcm/driver.go
- sinks/influxdb/driver.go
- sources/api/types.go
- sources/cadvisor.go
- sources/datasource/kubelet.go
- sources/kube_events.go
- sources/kube_nodes.go
- sources/kube_pods.go
It was pushing data to only one sink.
Made external sinks push data in parallel.
Improved debuggability.
> Fixed a bug in external sink manager 

- deploy/kube-config/influxdb/heapster-service.json
/cc @vishh 
We should have json validator run for these. Will file an issue.
> Remove extraneous comma

- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- version/version.go
/cc @rjnagal since @vishh is out
> Releasing v0.13.0

- sources/datasource/kubelet.go
- sources/kube_nodes.go
resubmitting to resolve CLA issue
> corrected typos and phrasing of error messages

- Makefile
- sources/nodes/kube.go
> Allow IP address as node name

- docs/coreos.md
Couldn't get heapster to properly work on coreos until I made the following changes.
> Fixing coreos docs for proper operation.

- sinks/api/decoder_v2_test.go
- sinks/cache/cache_impl.go
- sinks/cache/cache_impl_test.go
- sinks/cache/gc_store.go
- sinks/cache/gc_store_test.go
- sinks/cache/in_memory.go
- sinks/cache/time_store.go
Fixed a few bugs in the cache.
> Adding unit tests for the cache.

- docs/storage-schema.md
- sinks/api/decoder_test.go
- sinks/api/decoder_v2_test.go
- sinks/api/supported_metrics.go
> Add major page fault metric

- api/v1/api.go
> Compress output of /metric-export.

- Makefile
- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- version/version.go
> Releasing heapster v0.14.0.

- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
> Update to latest heapster release v0.14.0

- Makefile
- sinks/api/decoder_test.go
- sinks/api/decoder_v2_test.go
- sinks/api/supported_metrics.go
It needs to expose millicores and not shares.
> Fix cpu/limit metric calculation. 

- api/v1/api.go
- sinks/api/decoder.go
- sinks/api/decoder_v2.go
- sinks/api/supported_labels.go
- sinks/cache/cache.go
- sinks/cache/cache_impl.go
- sources/api/types.go
- sources/kube_nodes.go
- sources/nodes/coreos_test.go
- sources/nodes/kube.go
- sources/nodes/types.go
- sources/pods.go
Fixed issue where metric specific labels were not being populated in the API.
> Adding External ID as a label

- docs/storage-schema.md
- integration/heapster_api_test.go
> Updating docs with new labels being added.

- Makefile
- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
- version/version.go
Depends on #346 
The images have not been built and pushed. Kindly LGTM and wait for the images to be pushed before merging this PR.
> Releasing heapster v0.14.1

- sinks/api/decoder_v2.go
Fixes #348 
cc @a-robinson @rjnagal
> Fix issue with exporting host_id for pod containers.

- Makefile
- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
- version/version.go
> Releasing heapster v0.14.2

- sinks/api/decoder_v2.go
- sinks/cache/cache_impl.go
- sources/kube_pods.go
> Fixing "host_id" label for real.

- Makefile
- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
- version/version.go
> Merge releases v0.14.3

- sinks/cache/cache_impl.go
- store/gc_store.go
- store/gc_store_test.go
- store/in_memory.go
- store/in_memory_test.go
- store/time_store.go
cc @vishh 
Updated TimeStore.Get method to return structs of timestamp and value
> Update TimeStore to return timestamp-value pairs

- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
- version/version.go
> Updating heapster release to v0.15.0

- docs/sink-configuration.md
- sinks/gcm/core.go
- sinks/gcm/driver.go
- sinks/gcm/rate_metrics.go
- sinks/gcmautoscaling/driver.go
- sinks/modules.go
Need more work. Especially documentation update.
@vishh, could you please take a look before your vacation and then reassign to someone else?
> Added new sink for autoscaling purposes.

- docs/coreos.md
update instructions on starting cadvisor
> Update CoreOS docs

- Makefile
> Fix typo in Heapster InfluxDB Container creation command

- Makefile
- deploy/docker/build.sh
- integration/heapster_api_test.go
- integration/utils.go
These don't change much really, but bugged me :)
> Makefile fixes

- sinks/gcmautoscaling/driver.go
cc @vmarmol @vishh @jszczepkowski
> Added exporting nodes reservation metrics for Autoscaling sink

- heapster.go
- manager/manager.go
- sources/api/types.go
- sources/cadvisor.go
- sources/cadvisor_test.go
- sources/datasource/cadvisor.go
- sources/datasource/cadvisor_test.go
- sources/datasource/kubelet.go
- sources/datasource/kubelet_test.go
- sources/datasource/types.go
- sources/datasource/utils.go
- sources/datasource/utils_test.go
- sources/kube_events.go
- sources/kube_events_test.go
- sources/kube_nodes.go
- sources/kube_pods.go
- sources/kube_pods_test.go
- sources/test_utils.go
This is required to add a possibility of aggregating stats for node/cluster
needed for autoscaling purposes.
> Added aligning stats timestamps to multiple of resolution

- .travis.yml
> Ask Travis to use their new faster infra.

- sources/kube_nodes.go
- sources/nodes/coreos_test.go
- sources/nodes/kube.go
- sources/nodes/types.go
> Added exporting cpu/mem limits based on Kubernetes rather than cadvisor

- docs/sink-configuration.md
> Add curl example to sink configuration docs

- api/v1/api.go
- integration/.jenkins.sh
- integration/framework.go
- integration/heapster_api_test.go
```
% godep go test -v -retries 3 --timeout=5m '--vmodule=*=2'
=== RUN TestHeapster
I0722 17:48:11.240633   22204 heapster_api_test.go:110] built and pushed heapster image
--- PASS: TestHeapster (50.15s)
PASS
ok      github.com/GoogleCloudPlatform/heapster/integration     50.159s
```
Need I say more? :)
> Fix integration tests

- manager/manager.go
> Added aligning scraping range in addition to stats timestamps

- deploy/kube-config/google/heapster-controller.json
As requested in https://github.com/GoogleCloudPlatform/kubernetes/pull/12098
> Added ssl certs to kube-config google.

- extpoints/interfaces.go
- heapster.go
- manager/manager.go
- sinks/cache/cache.go
- sinks/cache/cache_impl.go
- sinks/cache/cache_impl_test.go
- sources.go
- sources/cadvisor.go
- sources/kube_events.go
- sources/kube_events_test.go
- sources/kube_factory.go
- store/time_store.go
This PR will pave way for making the cache the central source of information for the API, model and sinks.
cc @afein
> Adding events to cache.

- heapster.go
- model/impl_test.go
- sinks/cache/cache_impl.go
- sinks/cache/cache_impl_test.go
- sources/kube_events_test.go
Fixes #446.
cc @a-robinson @afein @mvdan
> Fix cache garbage collection 

- Makefile
- RELEASES.md
- heapster.go
- manager/manager.go
- schema/impl_test.go
- sinks/cache/cache.go
- sinks/cache/cache_impl.go
- sinks/cache/cache_impl_test.go
- version/version.go
> Cherry picks for v0.16.1

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/google/cadvisor/info/v1/container.go
- Godeps/_workspace/src/github.com/google/cadvisor/info/v1/machine.go
- Godeps/_workspace/src/github.com/google/cadvisor/info/v1/metric.go
> Updated CAdvisor godep to current master

- deploy/kube-config/influxdb/heapster-controller.json
> Remove merge artifacts from heapster-controller.json

- api/v1/model_handlers.go
Addresses #463. 
\cc @vishh @mvdan
> Added return statements after API error handling

- README.md
- docs/model.md
This PR documents the usage and API endpoints of the Heapster model. I plan to add one more documentation file on Heapster regarding contributions to the model later today.
\cc @vishh @mvdan
> Model API documentation

- sinks/cache/cache_impl.go
- sinks/cache/cache_impl_test.go
> Attempt to fix flaky cache impl tests

- Makefile
- deploy/docker/Dockerfile
- sinks/external_test.go
cc @mikedanese: I assume this will actually resolve the cert issues.
> Updating base docker image to alpine.

- docs/source-configuration.md
> add more documenation on how to setup the kubernetes source

- heapster.go
- manager/manager.go
- sources/api/types.go
- sources/cadvisor.go
- sources/cadvisor_test.go
- sources/datasource/cadvisor.go
- sources/datasource/cadvisor_test.go
- sources/datasource/kubelet.go
- sources/datasource/kubelet_test.go
- sources/datasource/types.go
- sources/datasource/utils.go
- sources/datasource/utils_test.go
- sources/kube_events.go
- sources/kube_events_test.go
- sources/kube_nodes.go
- sources/kube_pods.go
- sources/kube_pods_test.go
- sources/test_utils.go
Follow up https://github.com/kubernetes/kubernetes/pull/12793
> Removed align_timestamp flag

- hooks/check_boilerplate.sh
- store/daystore/day_store.go
- store/daystore/day_store_test.go
- store/statstore/stat_store.go
- store/statstore/stat_store_test.go
- third_party/window/LICENSE
- third_party/window/window.go
Please let me know what the appropriate policy is on adding modified third-party code. In this case, I had to modify https://github.com/jbrukh/window to support hourEntry structs instead of float64.
\cc @vishh @mvdan
> DayStore implementation

- sinks/cache/cache_impl.go
This fixes the flaky test TestRealCacheData.
> Add missing lastUpdated initialisation

- heapster.go
- sinks/external.go
- sinks/external_test.go
Fixes #509 
Added some validation for cache and sink durations. 
Ping @piosz @mvdan
> Fix race between sources and sinks

- model/util.go
- model/util_test.go
> FS epsilon handling

- Makefile
- RELEASES.md
- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
- version/version.go
> Release 0.18.0

- deploy/kube-config/influxdb/influxdb-grafana-controller.json
- influxdb/Dockerfile
- influxdb/RELEASES.md
Cherrypicking into v0.18 release
> Upgrading to InfluxDB v0.8.9

- integration/heapster_api_test.go
For integration test. Fixes #547.
> GCE zone flag

- docs/source-configuration.md
fix some typo error of docker.md
> fix some typo error of docker.md

- docs/debugging.md
fix the dead link of debugging.md
> fix the dead link of debugging.md

- api/v1/api.go
- api/v1/model_handlers.go
- handlers.go
- sources/kube_events.go
- sources/kube_nodes.go
- sources/kube_pods.go
> RunningInKuberenes flag (used in API handler registration)

- docs/standalone.md
fix some syntax and typo error in docs
> fix some syntax and typo error in docs

- docs/model.md
remove the unnecessary notice of model.md
> remove the unnecessary notice of model.md

- version/version.go
> Updating in-binary version to v0.18.1

- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone-test/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
> Updating kubernetes source configs to include naemspace scope in DNS name

- docs/model.md
- docs/standalone.md
> Updating docs.

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client_test.go
- docs/sink-configuration.md
- sinks/hawkular/driver.go
- sinks/hawkular/driver_test.go
New features
* Add token authentication support and support for SSL connections
Tests
* Integration testing should use init() method to test its behaviour also
Bugs
* Fix StoreTimeseries pointer mess up in calling registerIfNecessary with goroutine
Misc
* Update Hawkular-Metrics driver to 0.5.1
> Secure connections to the Hawkular-Metrics

- .travis.yml
- Makefile
- integration/.jenkins.sh
This should also make Travis run noticeably faster.
> Travis and Jenkins fixes

- expapi/v2/api.go
- expapi/v2/metrics_handlers.go
- expapi/v2/types/metrics_types.go
- handlers.go
> Add nodeMetrics expapi/v2 endpoint

- deploy/docker/canary/Dockerfile
> Adding a dockerfile to release canary images on every commit.

- deploy/kube-config/influxdb/influxdb-grafana-controller.json
- grafana/Makefile
- grafana/RELEASES.md
> Updating grafana image.

- sources/datasource/kubelet.go
> Fix raw container stats retrieval from kubelet over https

- README.md
- docs/roadmap.md
Updated readme to include a link to kubedash.
> Adding a roadmap.

- sinks/hawkular/driver_test.go
Fixes the issue #653 by adding a mutex for httptest server.
> Add mutex around shared objects outside httpserver goroutine

- README.md
- docs/sink-configuration.md
> Fix OpenShift case

- sources/kube_factory.go
> Ensure insecure can be used with k8s in cluster config

- docs/debugging.md
file link is yaml not json, fix it.
> fix wrong file link in debugging.md

- docs/influxdb.md
Just noticed this broken link while I was setting this up on my box.
> Updated Controller Spec link to yaml version

- sinks/hawkular/driver.go
remove the type of constant string variables.
> remove the type of constant variables

- docs/standalone.md
replace `kubernetes/heapster` with `k8s.io/heapster`
> fix the git repo path error

- deploy/kube-config/google/heapster-controller.yaml
fixes #702 
@chrislovecnm @mwielgus @vishh
> Fixed the value of stats_resolution in google/heapster-controller config

- docs/sink-configuration.md
modify the title of configuring sinks doc
> modify the title of configuring sinks doc

- docs/debugging.md
add `Time synchronization Problems` for debugging.md
refer the issues https://github.com/kubernetes/heapster/issues/802
> add `Time synchronization Problems`

- docs/influxdb.md
> Update influxdb docs

- grafana/dashboards/containers.json
Should fix #759 now that Heapster v0.19 has landed.
> Set suitable interval for CPU metrics

- grafana/dashboards/containers.json
> Fix container aggregation

- manager/manager.go
- sources/datasource/kubelet.go
Fixes #368 
Dirty: using leaky infra container name, regex for container name to pod mapping, but seems to work OK...
/cc @vishh @akash010 @smarterclayton @simon3z
> Expose network stats for pods

- common/influxdb/dummy_influxdb.go
- events/sinks/influxdb/influxdb_test.go
- metrics/sinks/influxdb/influxdb_test.go
- metrics/sources/kubelet/kubelet_test.go
Add testcase for influxDB sink and source/kubelet 
fixed https://github.com/kubernetes/heapster/issues/827
> Add testcase for influxDB sink and source/kubelet

- metrics/sources/kubelet/kubelet.go
- metrics/sources/kubelet/kubelet_test.go
Partial fix for #937 (other fixes in separate PR)
> Support legacy node IP address

- sinks/riemann/driver.go
> Fixes #944 Riemann sink panics on backend connection loss

- metrics/heapster.go
Resolves https://github.com/kubernetes/heapster/issues/967
> Add back in support for client based authentication.

- integration/framework.go
Somehow heapster jenkins nodes got into a state where the kubernetes tmp directory was present but empty. By checking for the actual required files rather than the directory, this should avoid such problems in the future.
See https://github.com/kubernetes/heapster/pull/982 for problematic build logs.
/cc @vishh @pwittrock
> More robust file checks for setting up integration tests

- sinks/opentsdb/driver.go
As stated in the OpenTSDB documentation 
```
Metric names, tag names and tag values have to be made of alpha numeric characters, dash "-", underscore "_", period ".", and forward slash "/"
```
At the moment, this is not honored by the opentsdb sink. 
This contribution intends to address this issue.
Note: this pull request replaces #999, which I submitted from the wrong github account.
> opentsdb sink: scrub identifiers from disallowed characters

- Makefile
- docs/source-configuration.md
- integration/.jenkins.sh
- metrics/api/v1/api.go
- metrics/core/labels.go
> Export disk metrics as part of `/metrics-export` endpoint

- deploy/docker/Dockerfile
> Use more recent version of glibc.

- integration/framework.go
- integration/heapster_api_test.go
> Integration tests for all pods in namespace, all nodes and label selector

- metrics/processors/node_autoscaling_enricher.go
Add node labels for metrics with type node. For more info see #1246
> add node labels for metrics with type node

- grafana/run.sh
Grafana can be configured via environment variables to serve via HTTPS. Detect this in the run.sh script and update the curl endpoints accordingly.
> Enable run.sh to talk via HTTPS if that's what Grafana is configured for

- Godeps/Godeps.json
- metrics/apis/metrics/handlers.go
- metrics/heapster.go
- vendor/k8s.io/kubernetes/pkg/healthz/doc.go
- vendor/k8s.io/kubernetes/pkg/healthz/healthz.go
Create a "/healthz" endpoint and a handler checking whether the latest data batch was gathered within a given period and whether there are any metrics available.
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1271)
> Add "/healthz" endpoint to Heapster.

- Makefile
- version/version.go
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1275)
> Release 1.2.0-beta.2

- docs/influxdb.md
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1346)
> Fixed a typo in docs link

- docs/debugging.md
- docs/overview.md
- docs/proposals/old-timer.md
- docs/proposals/push-metrics.md
- docs/proposals/vision.md
- docs/source-configuration.md
- docs/storage-schema.md
Correct several spelling mistakes in the documentation.
> spelling errors

- deploy/kube-config/standalone-with-apiserver/common.sh
- docs/source-configuration.md
- docs/storage-schema.md
- events/core/types.go
- events/manager/manager.go
- metrics/core/types.go
- metrics/sinks/hawkular/client.go
- metrics/sinks/influxdb/influxdb_historical.go
- metrics/sinks/metric/metric_sink.go
- metrics/sinks/monasca/keystone_client.go
- metrics/sources/kubelet/kubelet_client.go
Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>
> fix some typos

- README.md
I think that IRC channel is deprecated, move people to slack.
> README: discussion to slack and kubernetes-dev

- common/kubernetes/configs.go
Changed the function `GetKubeClientConfig`  to use `NewNonInteractiveClientConfig` instead of `NewNonInteractiveDeferredLoadingClientConfig` as we do not want to fallback to inClusterConfig if authFile is specified, for heapster standalone mode. This is required because heapster could be running on an overlay cluster and we do not want to fallback to inClusterConfig which would make heapster talk to the underlay apiserver instead of the overlay one.
(Inspired from this example https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/bootstrap.go#L149)
cc @piosz
> Made authFile override logic not fallback to in-cluster config for standalone mode

- Makefile
- integration/heapster_api_test.go
To fix the integration test under new image
> Add --test-user flag to integration test, default to jenkins if the run is triggered from docker image

- metrics/sinks/stackdriver/stackdriver.go
Fix memory/limit metric source for nodes (to be rebased & merged after #1550)
> Memory limit metric

- Makefile
- common/librato/dummy_librato.go
- common/librato/librato.go
- common/librato/librato_test.go
- docs/sink-configuration.md
- docs/sink-owners.md
- metrics/api/v1/historical_handlers_test.go
- metrics/sinks/factory.go
- metrics/sinks/librato/librato.go
- metrics/sinks/librato/librato_test.go
Sink for https://www.librato.com/
> Heapster Librato sink

- docs/sink-configuration.md
- metrics/sinks/opentsdb/driver.go
- metrics/sinks/opentsdb/driver_test.go
Fixes #1521
* added `cluster` param 
* updated docs
* removed unecessary methods: `DebugInfo` and `secureTags`
> Support of Environment label #1521

- metrics/sinks/influxdb/influxdb.go
> remove empty tag when sinking data to influxdb

- docs/sink-configuration.md
This PR updates the documentation on how to use the Librato sink.
> Fix documentation on how to use librato sink

- metrics/sources/kubelet/kubelet.go
I found that it is a little bit time-costing to understand the code part changed.
So I tried to refactor code to utilize return fast to make code more readable
What I did:
1. refactor code to utilize return fast to make code more readable
Signed-off-by: allencloud <allen.sun@daocloud.io>
> refactor code to utilize return fast to make code more readable

- docs/influxdb.md
According to https://github.com/kubernetes/heapster/issues/1652#issuecomment-314272083 It would be great to fix documentation.
It fixed my issue with clean Grafana. I am sure this will save a lot of time for newcomers.
> Fix to documentation 

- grafana/setup_grafana.go
> Fix minor typo

- docs/model.md
fix document of heapster argument metric_resolution
> fix typo metric_resolution argument

- Makefile
- grafana/Makefile
- influxdb/Makefile
Context: https://github.com/kubernetes/kubernetes/pull/57824
xref kubernetes/release#281
> Pushes go to staging-k8s.gcr.io

- common/kafka/kafka.go
@Kokan Is that better? :)
Close #1928
> [Kafka Sink] Clean function name
