kubernetes/heapster

- deploy/build-test.sh
- deploy/build.sh
- influx-grafana/grafana/build-test.sh
- influx-grafana/grafana/build.sh
- influx-grafana/influxdb/build-test.sh
- influx-grafana/influxdb/build.sh
- integration/.jenkins.sh
The script will shrink over time and the go tests will take over building and deploying the docker images.
> Moving jenkins runtime scripts to inside the repo.

- sinks/influxdb.go
- sources/external.go
- sources/kube.go
Ideally, we want to have a validate endpoint for heapster. But we need to expose a port for that.
Not sure if its worth just for debugging info and if there's a lighter solution.
> Add some debug information to heapster startup.

- sinks/influxdb.go
- sources/kube.go
Sample output:
Heapster Version: 0.5
Source type: Kube
Using kubelet port "10250"
Supported kubelet versions [v0.3]
Healthy Nodes:
kubernetes-minion-1.c.vishnuk-cloud.internal
kubernetes-minion-2.c.vishnuk-cloud.internal
No node errors
No pod errors
Sink type: Influxdb
client: Host "10.0.113.151:8085", Database "k8s"
Data buffering duration: 10s
Number of write failures: 4
> Add internal state of heapster to validate endpoint.

- integration/.jenkins.sh
- integration/kube_test.go
- sources/kube.go
- sources/types.go
Fixes #31.
This PR breaks backwards compatibility since the new kubelet API is available only from versions 0.9.0. Users who run older clusters can use an older version of heapster though.
> Support kube namespaces 

- sources/kube.go
- sources/types.go
Currently this is hard coded as http. This PR lets user specify URL including protocol to use, defaulting to http so as not to affect existing users.
> Allow https kube master

- sinks/gcm.go
- sinks/gcm/driver.go
- sinks/gcm/metrics.go
Also don't push metrics older than the last metric we pushed.
> Push GCM metrics as we generate them.

- sources/pods.go
This is required to handle situations when HostIP is not populated by the master on Pod objects.
> Remove HostIP check while filtering pods. 

- sinks/gcm.go
- sinks/gcm/metrics.go
This metric is computed versus the container start time.
> Add uptime metric to GCM sink.

- deploy/influxdb-grafana-controller.yaml
- influx-grafana/grafana/set_influx_db.sh
Since the new version of Heapster came out I've been troubleshooting an issue with Grafana in my bare metal Kubernetes cluster.  In the previous version, I was accessing the Grafana frontend directly from the pod IP address.  Since the access method changed to using the Kubernetes API server to access Grafana through the monitoring-grafana service the back end DB queries werent working.  The Grafana graphs were just spinning.  Looking at the web queries I saw that the issue was with API server trying to pull the data through the monitoring-influxdb service.  The issue is that by default the Kubernetes API service runs on port 8443 and the calls to the monitoring-influxdb service weren't specifying a port.  
I suggest the following changes....
-Add another ENV variable to the pod …
> Add in support for Kubernetes API service port

- integration/.jenkins.sh
Its time to do all this in golang and not get bitten by bash in the future.
> Fix exit code issue in jenkins integration test script.

- sinks/gcm/metrics.go
Added TODO for the remaining two types: diskIO and FS. DiskIO we may
not need yet and FS requires more infrastructure.
> Adding network metrics to GCM sink.

- docs/integration.md
- integration/framework.go
- integration/kube_test.go
- integration/utils.go
Integration test created temporary files on cluster nodes. Remove them.
Cleanup unused containers and images from kubernetes nodes.
Added a doc for integration testing against local cluster.
> Remove temporary files created by the integration test 

- deploy/run.sh
Default is influxdb which mirrors today's behavior.
Fixes #117.
> Use GCM sink if SINK=gcm is specified.

- sources/nodes/external.go
- sources/nodes/external_test.go
Replaces the old method of specifying an empty external hosts file to an
explicit --standalone flag.
> Support standalone mode throught the --standalone flag.

- sinks/influxdb/driver.go
- sinks/influxdb/sequence_number.go
- sinks/influxdb/sequence_number_test.go
This is required for proper ordering of cpu cumulative stats. Without this computing instantaneous cpu usage seems to be error prone.
> Adding Influxdb sequence number generator

- deploy/kube-config/v1beta3/influxdb-grafana-controller.yaml
This patch adds the port to the influxdb host and removes the url path (/api/v1beta1/proxy/...) that is already included inside the run.sh script of heapster_grafana:v0.5.
> deploy: update INFLUXDB_HOST including the port

- Makefile
- sources/api/types.go
- sources/events.go
- sources/kube.go
- sources/kube_test.go
This implements the first part of #118 Follow up PR will handle events from the sink side.
Related Kubernetes Issues:
* GoogleCloudPlatform/kubernetes/issues/4432
* GoogleCloudPlatform/kubernetes/issues/5638
> Add events source to heapster

- sources/kube.go
Missed when I added the kube clientauth piece - useful to be able to override insecure flag with command flag.
> Add back in command line insecure flag client config

- sources/nodes/kube.go
This commit makes heapster use the external ip in GCE.
This reverts commit aa206c499f187984db9761080df7aa01cb0b5627.
> Revert "Use node legacy host ip on older kubernetes versions"

- RELEASES.md
- docs/storage-schema.md
- sinks/api/decoder.go
- sinks/api/decoder_test.go
- sinks/api/supported_labels.go
- sinks/api/supported_metrics.go
- sinks/api/types.go
Note that support in cadvisor for docker container fs metrics is not complete. 
@vmarmol @rjnagal: I have chosen 'resource_id' as the label to uniquely identify sub-resource types like network cards and filesystem partitions. Any thoughts?
> Adding filesystem metrics

- .gitignore
- .travis.yml
- hooks/coverage.sh
This PR adds code coverage script that will be run on travis when the build runs. Good to know details like this going forward. We can also use https://coveralls.io by specifying a coveralls token & coveralls will feed back to PRs if configured to.
Also updated gofmt script line to fail build if any files needed go fmt'ing - before this would have just been info but passed.
> Add code coverage

- sinks/api/decoder_test.go
- sinks/api/supported_metrics.go
A couple of fixes:
* Expected and actual were flipped.
* Uptime test was calling `time.Since` and comparing to a `time.Since` value generated in the code without fixing the creation or current times. It works most of the time because the delta is usually 0, but is  non-deterministic.
> Fix metrics decoder uptime test

- .gitignore
- Makefile
- README.md
- deploy/docker/run.sh
- docs/source-configuration.md
- extpoints/interfaces.go
- flags.go
- heapster.go
- integration/.jenkins.sh
- modules.go
- sources.go
- sources/cadvisor.go
- sources/cadvisor_test.go
- sources/datasource/cadvisor.go
- sources/datasource/kubelet.go
- sources/datasource/types.go
- sources/kube_factory.go
- sources/kube_nodes.go
- sources/kube_pods.go
- sources/kube_pods_test.go
- sources/nodes/coreos.go
- sources/nodes/external.go
- sources/nodes/external_test.go
Fixes #197.
This PR switches to an easier way to create pluggable sources as well as allowing for multiple sources on the command line if required. Following @vishh's refactoring to source factories, this is the next logical step IMO, allowing source factories to be registered & then created in  a consistent way. This makes it easier for sources to be contributed without the need to add command line flags for each new source.
Sources are configured on the command line via the flag:
--source=<registered_source_prefix>:<source_uri>?<source_options>
The `--source` flag can be specified multiple times if necessary.
As a concrete example, if you are using the `kubernetes` source you would specify:
--source=kubernetes:https://localhost:8443?insecure=true
Each source is identified with a prefix …
> Easier pluggable sources & multiple sources on cmd line

- deploy/kube-config/influxdb/v1beta3/grafana-service.yaml
- deploy/kube-config/influxdb/v1beta3/heapster-service.yaml
- deploy/kube-config/influxdb/v1beta3/influxdb-grafana-controller.yaml
- deploy/kube-config/influxdb/v1beta3/influxdb-service.yaml
- deploy/kube-config/influxdb/v1beta3/influxdb-ui-service.yaml
Once a new kube release is out, I will update the e2e to use the v1beta3 configs by default. For now, the reviewer will have to trust that I tested this config manually!
> Update v1beta3 configs.

- integration/kube_test.go
- sinks/api/decoder.go
- sinks/api/decoder_test.go
- sinks/api/supported_labels.go
- sinks/api/supported_metrics.go
- sinks/api/types.go
- sinks/external.go
- sinks/gcm/driver.go
- sinks/influxdb/driver.go
- sinks/influxdb/driver_test.go
- sources/kube_factory.go
This implements the second part of #118 (follow up to PR #192).
Related Kubernetes Issues:
* GoogleCloudPlatform/kubernetes/issues/4432
* GoogleCloudPlatform/kubernetes/issues/5638
Screenshot showing events in InfluxDB (pulled by heapster from Kubernetes API server and pushed by heapster to influxdb):
Branched from #205
CC @vishh
> Heapster sink events to InfluxDB

- sinks/influxdb/driver.go
- sinks/influxdb/driver_test.go
Avoid duplicate kube events in InfluxDB by deterministically setting `sequence_number` value for each event.
Closes #250
> Avoid duplicate kube events in InfluxDB

- deploy/kube-config/influxdb/influxdb-grafana-controller.json
- docs/influxdb.md
I noticed that the kubectl deploy for influxdb did not work - the external and internal URL and version of API was incorrect.
> Fixed URL in influxdb kube-config and updated readme

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client_test.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/helpers.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/types.go
- docs/sink-configuration.md
- docs/storage-schema.md
- sinks/hawkular/driver.go
- sinks/hawkular/driver_test.go
- sinks/modules.go
This PR provides support for pushing numerical metrics to the Hawkular-Metrics (http://www.hawkular.org/) for monitoring purposes. The Hawkular-Metrics endpoints can be used standalone or with a full Hawkular 
github.com/hawkular/hawkular-client-go/metrics is a required dependency.
> Support for Hawkular-Metrics sink.

- heapster.go
Rewrote three flag help messages to resolve typos and to better clarify what they represent.
> Rewrote flag usage messages for clarity

- Makefile
Vet is now part of the golang distribution, through the go.tools subdirectory. 
Therefore, the dependency should be satisfied by the go distribution itself, rather than go get.
> Removed go vet dependency

- schema/types.go
- sinks/cache/cache_impl.go
- store/gc_store.go
- store/gc_store_test.go
- store/in_memory.go
- store/in_memory_test.go
- store/time_store.go
This PR moves the definition and implementations of TimeStores outside of the cache package, along with related references. 
Sidenote: There might be confusion between store.gcStore and utils.gcstore.GCStore
> Move TimeStore definition and implementations outside of cache module

- schema/impl.go
- schema/impl_test.go
- schema/types.go
- schema/util.go
- schema/util_test.go
Part 3 of #342 
Includes the following:
- Add methods for Namespaces, Nodes and Pods
- Unit tests for adders and the existing util functions
Changes based on comments from #358:
- lock moved inside the cluster object again
- Get methods have more verbose comments, clearly explaining inputs and outputs
@vishh @rjnagal the next PR, Schema 4, will include utility functions that operate on TimeStores, along with their unit tests.
> [Schema 3] Adders and Unit Tests

- schema/impl.go
- schema/impl_test.go
- schema/types.go
- schema/util_test.go
Part 4 of #342 
This PR addresses the population of an InfoType element from a cache.ContainerElement.
This involves all the TimeStore-related functionality of the implementation.
Additions (at 100% test coverage):
- updateInfoType: populates an InfoType from a ContainerElement
- parseMetric: populates a map[string]*TimeStore from a ContainerMetricElement
- addMetricToMap: adds a single metric to a map[string]*TimeStore
Fundamental change - Feedback required:
realCluster now contains a tsConstructor: func() (store.TimeStore) field, meant to be populated by the caller. 
+ This effectively decouples the TimeStore implementation and its duration from the realCluster.
- The three new functions (updateInfoType, parseMetric, addMetricToMap) need to be realCluster methods, in order to have …
> [Schema 4] Timestore-related functionality and unit tests

- schema/impl.go
- schema/impl_test.go
- schema/types.go
- schema/util.go
- schema/util_test.go
Part 5 of #342 
This PR implements the Update(Cache) method along with all appropriate submethods.
The Update method introduces the functionality of populating the cluster with new metrics from a Cache.
In the next PR, the Update method will be extended to also extract aggregated metrics (but not derived stats yet)
Additions (with test coverage %):
- Update(*Cache): updates the cluster from a *Cache. (87.5%)
- updateNode: updates/adds a node in the cluster from a *ContainerElement. (100%)
- updatePod: updates/adds a pod in the cluster from a *PodElement. (93.3%)
- updatePodContainer: updates/adds a Pod Container from a *ContainerElement. (100%)
- updateFreeContainer: updates/adds a Free Container from a *ContainerElement. (100%)
- addContainerToMap (utility function): creates or finds a …
> [Schema 5] Update methods

- integration/heapster_api_test.go
- sinks/cache/cache_impl.go
- sources/kube_nodes.go
Essentially this PR removes the "/" prefix from system containers. Over time, we will have to update this logic to handle system containers in systemd systems.
The e2e test has been upgraded to capture the presence of system containers on all the hosts.
> Make the system container names user friendly

- grafana/kubernetes-dashboard.json
Currently the default Kubernetes Grafana dashboard does not show metrics correctly.
With this fix the dashboard looks like this:
> Fix Kubernetes Grafana Default Dashboard

- store/cma_store.go
- store/cma_store_test.go
Added a CMA TimeStore implementation, cma_store. 
All TimePoints in the cma_store have unique timestamps. When two or more TimePoints with the same timestamp are Put in the store, they are converted to a single TimePoint with a Value that represents the average of all TimePoints with the same timestamp.
cma_store can be used as the basis for a TimeStore that can maintain derived stats, as it is already making the assumption that Value is a uint64.
100% Test Coverage
cc @rjnagal @vishh
> Cumulative Moving Average TimeStore

- deploy/kube-config/google/heapster-service.json
- deploy/kube-config/influxdb/grafana-service.json
- deploy/kube-config/influxdb/heapster-service.json
- deploy/kube-config/influxdb/influxdb-grafana-controller.json
- deploy/kube-config/influxdb/influxdb-service.json
- deploy/kube-config/influxdb/influxdb-ui-service.json
- deploy/kube-config/standalone/heapster-service.json
- docs/influxdb.md
- docs/source-configuration.md
- integration/framework.go
- sources/kube_factory.go
- sources/pods.go
Kubernetes is going to stop exposing the v1beta3 API by default, so this need to switch to the new version.
See https://github.com/GoogleCloudPlatform/kubernetes/issues/10755
> Migrating to Kubernets API v1

- manager/manager.go
This should be merged and then pushed to Kubernetes ASAP because it may cause:
* exporting duplicated data
* increasing cpu/mem usage by Heapster due to increasing amount of data to process
> Fixed time range for collecting stats for every pass

- integration/framework.go
- integration/heapster_api_test.go
This would definitely be an issue for running the integration tests on
non-unix-like systems.
> Use filepaths for local file paths

- integration/heapster_api_test.go
If we always return at each iteration, we'll only ever test the first version.
Seems like a typo or silly mistake.
> Properly do all kubeVersions in the integration tests

- schema/aggregation.go
- schema/aggregation_test.go
- schema/impl.go
- schema/impl_test.go
- schema/types.go
- schema/util.go
- schema/util_test.go
- store/cma_store.go
Part 6 of #342 
This is #380, reopened due to ghost commits in the old PR.
This PR includes a full implementation of metric aggregation (summation) throughout the cluster structure.
New realCluster methods:
- aggregationStep: performs full aggregation of all entities in the structure, holds the cluster lock.
- aggregateNodeMetrics: sums Node metrics to generate Cluster metrics
- aggregateNamespaceMetrics: sums Pod metrics to generate Namespace metrics
- aggregatePodMetrics: sums Container metrics to generate Pod metrics
- aggregateMetrics: populates an InfoType by summing values from an []*InfoType
New utility functions:
- addTimePoints: adds the values of two TimePoints, returns a new TimePoint with the added value.
- popTPSlice: pops the first element of a []TimePoint.
- …
> [Schema 6] Metric Aggregation

- model/aggregation.go
- model/aggregation_test.go
- model/impl.go
- model/impl_test.go
- model/types.go
- model/util.go
- model/util_test.go
This PR renames the schema package to model, as it is a more fitting name and avoids confusion with actual schema references in the codebase.
From now on, all further PRs will be prefixed with [Model X]. Specifically, the next PR will be [Model 7], which will implement some basic cluster-level API endpoints.
\cc @rjnagal @vmarmol
> [Schema->Model] Rename the Schema package to Model

- deploy/docker/Dockerfile
fixes #381. Although we fixed this in kubernetes with a config change to the controller.json, we shouldn't rely on a host directory in the long term. CA crts we need should be embedded in the image. cc @piosz @vishh
> add CA certs to the docker image

- api/v1/api.go
- docs/sink-configuration.md
- heapster.go
- manager/manager.go
- manager/sinks.go
- sinks/api/v1/external_sink.go
- sinks/bigquery.go
- sinks/external.go
- sinks/external_test.go
- sinks/gcl/driver.go
- sinks/gcm/core.go
- sinks/gcm/driver.go
- sinks/gcmautoscaling/driver.go
- sinks/hawkular/driver.go
- sinks/influxdb/driver.go
- sinks/memory.go
- sinks/types.go
- validate/validate.go
Added a new API endpoint, /api/v1/sinks, that returns the sink uris on GET and
lets you set them via a POST. The sink uris work just like when you pass them
as flags.
Had to split the ExternalSinkManager interface into Sink for actual sinks and
ExternalSinkManager for the actual managers (only sinks/external.go for now).
The latter adds a new method, SetSinks(), which is what we use here.
Since sinks may now be removed at runtime, an Unregister() function in the
ExternalSink interface was added. The implementations have been left as TODOs
for now - what each one will do depends on the implementation, just like
Regsiter().
CC @vmarmol @vishh
> Add support for modifying sinks at runtime

- manager/manager.go
- sinks/cache/cache.go
This was causing the REST API to return nearly 10 minute old data due to the default 10 minute buffer in the GC store.
As a pretty strong disclaimer, I haven't actually tested this in a cluster and I didn't see any unit tests that it'd be easy to add a check for this to. The unit tests do all pass, however. I can spend some time trying to test it in a live cluster tomorrow if you'd like.
@vmarmol
> Fix onlyKeepLatestStat to return the latest rather than the oldest stat

- influxdb/run.sh
- integration/.jenkins.sh
Especially on the jenkins one, since we don't want to run the integration
tests if the unit tests already failed.
CC @vishh 
You can see an example of this problem here:
http://104.154.52.74/job/heapster-e2e-gce/1714/console
`make` fails, but `godep` is run anyway.
> Exit on any shell script errors equally on all scripts

- api/v1/model_handlers.go
- model/impl.go
- model/impl_test.go
- model/types.go
- model/util.go
- model/util_test.go
This is #420, reopened due to jenkins testing the wrong PR.
This PR is focused in 2 major changes to the model REST API:
Model GetXMetric methods now receive specific Request structs as parameters.
Added new Getters, endpoints and tests for extracting all nodes, namespaces, pods and containers from the model. This should allow API consumers to seamlessly
> [Model 8] REST API polishing, cleanup and extensions

- api/v1/model_handlers.go
- heapster.go
- manager/manager.go
- model/impl.go
- model/impl_test.go
- model/util.go
This PR finalizes the initial implementation of the model APIs for metrics, by adding sanity checks for edge cases in API calls and cpu usage calculation.
Also, the housekeeping of the model is now decoupled from that of the cache, which corrects some weird behaviors, such as values changing in both the past and future. The new housekeeping interval ensures that there is at least 1 datapoint per entity for each model resolution interval.
Please include this PR in the next release.
\cc @rjnagal @vishh
> [Model 9] Sentinels, housekeeping and improved cpu calculation

- deploy/kube-config/google/heapster-controller.json
- deploy/kube-config/influxdb/heapster-controller.json
- deploy/kube-config/standalone/heapster-controller.json
It's effectively the same thing, just more confusing.
> Remove redundant :'' from sources without url

- sinks/cache/cache_impl_test.go
Occured in travis:
https://travis-ci.org/GoogleCloudPlatform/heapster/builds/74985112
```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a ./...
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a
hooks/coverage.sh
?   	k8s.io/heapster	[no test files]
?   	k8s.io/heapster/api/v1	[no test files]
?   	k8s.io/heapster/clusters/coreos	[no test files]
?   	k8s.io/heapster/extpoints	[no test files]
ok  	k8s.io/heapster/integration	0.014s	coverage: 0.0% of statements
ok  	k8s.io/heapster/manager	0.011s	coverage: 22.4% of statements
ok  	k8s.io/heapster/model	0.033s	coverage: 96.6% of statements
ok  	k8s.io/heapster/sinks	0.013s	coverage: 31.2% of statements
ok  	k8s.io/heapster/sinks/api	0.019s	coverage: 98.2% of statements
ok  	k8s.io/heapster/sinks/api/v1	0.011s	coverage: 70.2% of …
```
> Fix nil dereference panic in cache_impl_test

- api/v1/api.go
- api/v1/model_handlers.go
- api/v1/types/model_types.go
- api/v1/types/types.go
- integration/heapster_api_test.go
- sinks/external_test.go
So that they can be imported in k8s without handlers etc.
> Movie API types to a separate package

- deploy/kube-config/influxdb/influxdb-service.json
This commit includes launching the influxdb service in kube system namespace so that heapster can push to influxdb. There was an error in the influxdb service spec file where default namespace was used.
> Launching the influxdb service in kube-system namespace

- store/daystore/day_store.go
- store/daystore/day_store_test.go
- store/statstore/stat_store.go
- store/statstore/stat_store_test.go
Part 1 of #478
This PR changes the behavior of the StatStore Get operation to also include one TimePoint that contains the Max of values stored in the current minute.
This behavior is needed to avoid metrics lagging behind after aggregation for abstract entities.
For example, if the latest timestamp is N minutes for all containers, then with the old behavior of Get the latest timestamp for pods would be N-1 and the latest timestamp for namespaces would be at N-2.
The behavior of Last has also changed to return values from LastPut.
- Last(true) now returns the Max value of the items represented in lastPut.
- Last(false) returns the average value of the items represented in lastPut
These two changes guarantee that the derived stats exposed by the heapster model are always sane, meaning that …
> Changed behavior of StatStore Get and Last

- sinks/external_test.go
> Remove sleeps from external_test.go

- deploy/kube-config/influxdb/influxdb-grafana-controller.json
- influxdb/Dockerfile
- influxdb/RELEASES.md
This is required for safely upgrading to InfluxDB v0.9
> Upgrading to InfluxDB v0.8.9

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/client_test.go
- Godeps/_workspace/src/github.com/hawkular/hawkular-client-go/metrics/types.go
- README.md
- docs/sink-configuration.md
- docs/storage-schema.md
- sinks/hawkular/driver.go
- sinks/hawkular/driver_test.go
This PR adds some changes to the Hawkular-Metrics sink described below. Some of the changes are done to provide better support for using Heapster on the Openshift v3, while others are fixes that did not work correctly in the first version. Do not merge yet, requires still an update to the Hawkular-Metrics client (to released version) - but open to comments.
New features:
* Add support for Cumulative metric type
* Add feature to transform metric label value to Hawkular-Metrics tenant
Tests:
* Add integration tests to check Register and Timeseries methods.
Improvements:
* Parallel Storetimeseries operations to improve performance when storing to multiple tenants
* Make registerIfNecessary happen in the background goroutine
Fixes:
* Fix registerIfNecessary leaking map reference between …
> Updates to the Hawkular-Metrics sink

- README.md
- docs/Grafana Dashboard.json
- docs/influxdb.md
Newer versions of Grafana do not support embedding dashboards into the image easily.
Updated main Readme along the way.
cc @dchen1107
> Adding a sample Grafana dashboard. 

- sinks/api/decoder.go
- sinks/cache/impl.go
This is useful for monitoring based on labels set to container images.
xref: https://github.com/kubernetes/kubernetes/pull/13612
cc @dchen1107
> Add container labels to the list of labels exported by heapster.

- docs/model.md
Some heapster's URLs of same type are end with different character. Some with "/", and another with not. Like this:
```
/api/v1/model/nodes/{node-name}/pods
```
different from:
```
/api/v1/model/nodes/{node-name}/metrics/
```
So , i want to unify it
> unify the format of restful api & fix some typo error 

- Godeps/Godeps.json
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/auth/authenticator/bearertoken/bearertoken.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/auth/authenticator/interfaces.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509/doc.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509/x509.go
- auth.go
- heapster.go
Heapster exposes unencrypted endpoints without authorization. In secure environments like OpenShift we'd like to secure the endpoints, both via TLS & by client certificate so that the master can use a certificate to authenticate for autoscaler stuff, etc.
This PR allows the configuration of TLS cert/key, client certificate checks & restricting users based on the CN of client cert. All optional of course.
Note that the godeps that have been updated are from a `godep restore` & `godep save ./... github.com/progrium/go-extpoints` to add in additional packages - I'm guessing some of the godep json had been updated manually prior to this.
/cc @mwringe @jcantrill @liggitt @pweil-
> Enable TLS option & client certificate authentication

- api/v1/api.go
- api/v1/model_handlers.go
- handlers.go
Current approach of forcing gzip encoding isn't very friendly to clients. With this approach clients can use standard `Accept-Encoding` header to request compress, either gzip or deflate, as provided by go-restful.
> Enable content encoding negotation

- sources/kube_events_test.go
As discussed offline with @vishh, this test is fundamentally broken and
doesn't test anything properly. It doesn't fail because the events list never
gets processed. If it does, #537 takes place since the events list is wrong.
Even if it doesn't, #565 can also appear.
Since the test is flawed and flaky, best remove it until it is rewritten
properly. Right now it's causing issues with pull requests since its flakyness
comes up often thanks to -race.
> Skip TestEventsBasic broken and flaky test

- deploy/kube-config/influxdb/influxdb-grafana-controller.yaml
- grafana/Dockerfile
- grafana/Makefile
- grafana/README.md
- grafana/RELEASES.md
- grafana/dashboards/cluster.json
- grafana/dashboards/containers.json
- grafana/run.sh
* Discover InfluxDB service endpoint and create a datasource using Grafana API.
* Import a couple of dashboards which use templating and repeated panels in Grafana 2.1.0.
* The dashboards pick up nodes, pods, and containers automatically with zero configurations.
> Grafana 2.1.0 and InfluxDB 0.9.4 Support E2E

- grafana/Dockerfile
- grafana/Makefile
- grafana/README.md
- grafana/RELEASES.md
- grafana/dashboards/cluster.json
- grafana/dashboards/containers.json
- grafana/run.sh
- Create a datasource for InfluxDB during startup.
- Import a couple of default dashboards, which use templating to discover hosts, pods and containers.
> Improved the out-of-the-box experience for Grafana

- docs/sink-configuration.md
- sinks/hawkular/driver.go
- sinks/hawkular/driver_test.go
This PR updates the Hawkular-Sink to support the following features:
* Password and username authentication
* If podId is missing (system metrics), use hostId in the naming
* Add filtering capabilities to avoid storing certain metrics
I think the filtering capabilities would be nice in the Heapster itself, however this would require a bit more planning and perhaps a query language designed with yacc or equal (this is very simple filtering language)
> Update Hawkular-Sink to support filtering

- deploy/docker/canary/Dockerfile
- deploy/kube-config/google/heapster-controller.yaml
- deploy/kube-config/influxdb/grafana-service.yaml
- deploy/kube-config/influxdb/heapster-controller.yaml
- deploy/kube-config/influxdb/influxdb-grafana-controller.yaml
- deploy/kube-config/standalone-test/heapster-controller.yaml
- deploy/kube-config/standalone/heapster-controller.yaml
`kubernetes/heapster:canary` image will be built and pushed every night.
Fixes #625
> Updating HEAD to use heapster canary image 

- docs/model.md
When I tried the node level metrics api of heapster according the api descriptions in current model.md, I found it was wrong. After correcting the wrong node level metrics api according to the modification in this pr, the heapster then can reply with right response.
> correct the node level metrics api

- sinks/cache/cache.go
I try to dig into the sources of heapster, and find some comments of interface Cache (in heapster/sinks/cache/cache.go line 91 and 97) may just copy from line 85, and if just
see the comments and method definition, user may get confused.
After reading the implementation in heapster/sinks/cache/impl.go, i modify the method comments 
of Cache, aiming at making the methods comments more readable and meaningful.
> correct the comments of interface Cache

- model/impl.go
- model/impl_test.go
I read into sources of heapster, and find out the comments of deleteFreeContainer in model/impl.go are just copy from the method updateFreeContainer, which will make confusion and be meaningless.
So I correct the comments of deleteFreeContainer (), and add the corresponding method test in model/impl_test.go.
> Correct comments of deleteFreeContainer and add corresponding test

- docs/sink-configuration.md
@vishh @jimmidyson 
As we discuss usage of multiple sinks in the end of (https://github.com/kubernetes/heapster/pull/712),
here is the pr to modify the sinks document to provide examples for using multiple sinks without changing current usage of `--sink` flag.
> add docs of the usage of multiple sinks

- docs/standalone.md
Removed a redundant quotation symbol from the standalone documentation
> Tiny Doc fix

- docs/google.md
with respect to where Container Engine metrics will be. Multiple users
have been confused by this doc.
@vishh
> Clarify the doc about getting set up with Google Cloud Monitoring

- grafana/Dockerfile
- grafana/Makefile
- grafana/run.sh
needed to add `--homepath` to grafana start args, other than that, just a simple version bump.
> grafana: bump version to 2.5.0

- metrics/api/v1/model_handlers.go
- metrics/core/prometheus_labels.go
- metrics/handlers.go
- metrics/heapster.go
- metrics/manager/manager.go
- metrics/processors/namespace_aggregator.go
- metrics/processors/pod_aggregator.go
- metrics/sources/kubelet/kubelet_client.go
- metrics/sources/manager.go
@mwielgus 
**Add status information to Heapster**
including:
+ time of the last metrics scrape
+ histogram of Kubelet/source response times
+ number of scraped nodes and containers
+ time spent in scrape (single run, not cumulative)
+ time spent in processors (single run, not cumulative)
+ time spent in exporting data to sinks (single run, not cumulative)
+ number of http model api requests
+ number of other http requests
> add prometheus for heapster

- grafana/Dockerfile
- grafana/Makefile
- grafana/RELEASES.md
- grafana/dashboards/cluster.json
- grafana/dashboards/containers.json
This PR includes the following changes to the default Dashboards:
* Grafana v7 schema
* Accurate CPU metrics
* Group metrics by time >30s (better than fixed value, adapts to time range and pixel width of the graph)
* Fix container metrics aggregation ("app" and "app-slave" metrics used to be wrongly aggregated)
* Clean leftovers from old versions (mainly obsolete settings)
> Update Grafana and default dashboards

- docs/sink-configuration.md
- metrics/sinks/hawkular/client.go
- metrics/sinks/hawkular/driver.go
- metrics/sinks/hawkular/driver_test.go
- metrics/sinks/hawkular/types.go
This PR adds the ability to send data in smaller batches to Hawkular-Metrics with increased or decreased concurrency. This setting is useful for example in scaled out situation with OpenShift where sending smaller batches with higher concurrency can balance the load between the Hawkular-Metrics nodes that are deployed.
There are two commits (to make review easier), first one is some refactoring from single driver.go to driver.go/client.go to make files smaller and easier to modify (driver.go is for stuff that is Heapster->Sink transforming and client.go is Sink->Hawkular-Metrics-Driver).
This one is for heapster-scalability branch.
> Adding batching capabilities and concurrency settings to Hawkular sink

- integration/heapster_api_test.go
- metrics/api/v1/model_handlers.go
- metrics/handlers.go
This makes the `/metrics/{metrics-name:*}` endpoint consistent with the names returned from `/metrics` & supports all available metrics for each resource type (cluster, node, pod, etc).
/cc @mwielgus @piosz
> Support all available metrics in REST API

- metrics/api/v1/api.go
Missed this in https://github.com/kubernetes/heapster/pull/927
/cc @vishh @mwielgus
> Handle 'delta' metrics in the API conversion

- metrics/processors/node_aggregator.go
- metrics/sources/manager.go
There are a bunch of messages that we are currently logging which could be moved to not being logged by default. This will prevent the logs from growing too much in size and will allow people to more easily parse through the logs to determine if something went wrong.
The logs about how many metrics were gathered have been moved to V(1) level instead of the default logging level.
If we don't have node level metrics, we shouldn't be filling up the logs with warning messages that we can't aggregate metrics for the non-existent metric. This has also been moved to V(1).
> Reduce when some of our messages get logged.

- common/influxdb/dummy_influxdb.go
- metrics/sinks/influxdb/influxdb.go
- metrics/sinks/influxdb/influxdb_historical.go
- metrics/sinks/influxdb/influxdb_test.go
`GetAggregation` and `GetLabeledAggregation` were missing one of the checks for missing data, and thus would panic when invalid pods were requested.  This fixes that.
Fixes #1249
> InfluxDB Historical: Fix panic on missing pods in GetAggregation

- README.md
Openshift repository includes instructions on how to run standalone Heapster or Heapster with Hawkular-Metrics combination on Openshift (with deployment scripts).
> Update README with correct Openshift instructions

- Makefile
* change `go build` to `go install` to pre-compile all dependencies
* check whether `godep` is already installed. If so, bypass `go get github.com/tools/godep`
For more info see #1256
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1257)
> reduce make build time

- grafana/Dockerfile
- grafana/Makefile
@piosz 
Updated grafana version to use with the new version of influxdb
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1342)
> Update grafana version

- docs/sink-configuration.md
I have test that when we use es sink to store metrics and events, we should specify the "http://" prefix, otherwise i got error like below with ElasticSearch 2.4.1, kibana 4.6.2 and eventer 1.2.0.
```
andy@localhost:~/go/src/k8s.io/heapster$ ./eventer -logtostderr=false -log_dir=/home/andy/log -v=4 -max_procs=4 --frequency=5s -sink="elasticsearch:?nodes=127.0.0.1:9200&Index=eventer&maxRetries=3" -source="kubernetes:http://127.0.0.1:8080?inClusterConfig=false"
E1110 15:28:38.747801   64037 factory.go:53] Failed to create sink: Failed to create ElasticSearch client: no Elasticsearch node available
```
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/ …
> fix es sink doc

- common/elasticsearch/mapping.go
Values should be double, as we found out in: https://github.com/elastic/elasticsearch/issues/21885
> HOTFIX: change value to be double [ES]

- common/elasticsearch/elasticsearch.go
- common/elasticsearch/elasticsearch_test.go
- common/elasticsearch/mapping.go
- docs/sink-configuration.md
- events/sinks/elasticsearch/driver.go
- events/sinks/elasticsearch/driver_test.go
- metrics/sinks/elasticsearch/driver.go
- metrics/sinks/elasticsearch/driver_test.go
fix #1383
This PR will add a new elasticsearch field `eventCluster`. A new eventer command line argument `cluster` is added to config the value for `eventCluster`.
Let me explain why we should add this option. Image that, we have one Kubernetes `A` cluster in one datacenter, i have set up one ES to collect the events from A Kubernetes cluster. Everything is OK. After some time we added the second Kubernetes cluster `B` in the same datacenter as Kubernetes `A`. We want also want to collect the events of cluster `B` using the same one ES as cluster `A`. This will make our ES operation more easy and stability with maintaining small ES clusters.  However, currently, we can not make a difference between events for cluster `A` and `B`. 
We can accomplish this by setting a `eventCluster` field …
> Add cluster tag for es event

- events/eventer.go
- metrics/sinks/factory.go
I have run into a situation where i configure an `es` cluster to store Kubernetes events and the `es` configuration is invalid. After checking that `eventer` is running through `systemctl --user status eventer.service`, i leave it there to run. After some days, when i need to query `es` about the recent events, nothing was collected.  
I turns out that the `es` configuration is invalid and an error is logged, but `eventer` continues to run without fail. As `es` is the only sink i configured, this makes `eventer` got no valid sinks and even Kubernetes emits some events, the events will not be sinked to `es`. 
This PR will make `eventer` and `heapster` fail faster when there is no valid sinks.
> fail fast when there is no available sinks

- Godeps/Godeps.json
- docs/sink-configuration.md
- metrics/sinks/factory.go
- metrics/sinks/graphite/driver.go
- metrics/sinks/graphite/driver_test.go
- vendor/github.com/marpaia/graphite-golang/.gitignore
- vendor/github.com/marpaia/graphite-golang/LICENSE
- vendor/github.com/marpaia/graphite-golang/README.md
- vendor/github.com/marpaia/graphite-golang/doc.go
- vendor/github.com/marpaia/graphite-golang/graphite.go
- vendor/github.com/marpaia/graphite-golang/metric.go
This changeset adds a basic graphite/carbon sink for metrics (fix #538)
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1341)
> Graphite metrics sink

- events/eventer.go
fix typos, improve description according to `runtime.GOMAXCPUS` and `runtime.NumCPU`'s descriptions
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>
> fix and improve arguments' description

- metrics/processors/helper.go
cluster_aggregator.go, node_aggregator.go, namespace_aggregator.go all call this function, so the error log 				"NamespaceAggregator" is inaccurate.
> fix error log

- docs/storage-schema.md
- integration/heapster_api_test.go
- metrics/core/metrics.go
This PR adds filesystem inode metrics:
* `filesystem/inodes`: The number of available inodes in a the filesystem
* `filesystem/inodes_free`: The number of free inodes remaining in a the filesystem
/cc @DirectXMan12  @piosz @kubernetes/heapster-reviewers
> add filesystem inode metrics

- docs/sink-configuration.md
- metrics/sinks/hawkular/client.go
- metrics/sinks/hawkular/driver.go
- metrics/sinks/hawkular/driver_test.go
- metrics/sinks/hawkular/types.go
Update to include labels as individual tags in Hawkular Metrics. This will make querying based on labels from Hawkular Metrics easier to use. The existing 'labels' tag which includes the comma separated list will still be stored.
> [Hawkular] Add labels as individual tags

- events/api/api.go
- events/api/handler.go
- events/eventer.go
- events/manager/manager.go
- events/sources/kubernetes/kubernetes_source.go
Fix #1293 .
This PR adds `/healthz` and `/metrics` http service to eventer.
* healthz endpoint currently only checks latest scrape time, if `LatestScrapeTime` is 3 minutes later than now, healthz endpoint will return with http response code being 500.
* metrics endpoint is used for Prometheus.
Note: **This PR needs to be merged after #1539 because newly added file's boilerplate is 2017. :). Currently this PR will not pass successfully, i will rebase this PR once #1539 is merged.**
/cc @AlmogBaku @DirectXMan12 @piosz @kubernetes/heapster-reviewers
> add healthz to eventer

- docs/sink-configuration.md
This matches the other formatting.
> Fix formatting of --sink=log example.

- common/influxdb/influxdb.go
- docs/sink-configuration.md
- events/sinks/influxdb/influxdb.go
- metrics/sinks/influxdb/influxdb.go
Fix #1632.
Add `cluster_name` tag to Influxdb for both heapster and eventer.
/cc @kubernetes/heapster-maintainers @kotarusv
> add cluster_name to influxdb sink

- common/elasticsearch/mapping.go
- docs/storage-schema.md
- grafana/dashboards/influxdb_withfields/pods.json
- grafana/dashboards/pods.json
- metrics/sinks/opentsdb/driver_test.go
This PR is followed by #1659.
I have forgot to grep `pod_namespace` usage instead of `LabelPodNamespace`. This PR will clean the usage about `pod_namespace`.
/ping @kubernetes/heapster-maintainers @piosz @DirectXMan12 
This also change code with ES, so @AlmogBaku PTAL.
> fix docs&&misc about delete pod_namespace

- metrics/sinks/influxdb/influxdb.go
According to [doc about `host_id`](https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md#labels), it is 
> Cloud-provider specified or user specified Identifier of a node
Since host_id is retrievable using the node name, host_id is redundant.
/cc @kubernetes/heapster-maintainers @piosz @DirectXMan12
> remove host_id from influxdb

- docs/sink-configuration.md
- metrics/sinks/hawkular/client.go
- metrics/sinks/hawkular/driver.go
- metrics/sinks/hawkular/driver_test.go
- metrics/sinks/hawkular/types.go
- vendor/github.com/hawkular/hawkular-client-go/metrics/client.go
- vendor/github.com/hawkular/hawkular-client-go/metrics/helpers.go
- vendor/github.com/hawkular/hawkular-client-go/metrics/types.go
* disablePreCache parameter set to true will prevent initial fetch of definitions from the metrics server (instead building it from the scratch when storing datapoints)
* Each time datapoint is stored, the tags are compared to see if there's an update (such as labels)
* Increase concurrency of registerLabeledIfNecessary with changes the mutexes (they only prevent concurrent cache modification now)
cc @mwringe
> Hawkular-sink updates to definition cache handling

- grafana/dashboards/pods.json
The current template for the Pods dashboard won't refresh the list of available namespace, leaving only `default` and `kube-system` as options. It took me some time to figure out why, because both _pod_ and _node_ selector (at the Cluster dashboard) were automatically reloading its values.
> Refresh namespace values at Pods dashboard

- common/elasticsearch/elasticsearch.go
- common/kafka/kafka.go
Signed-off-by: allencloud <allen.sun@daocloud.io>
What this PR did:
1. fix some nits in log, I think `failed to parse` is better than `failed to parser`.
> fix nits in log

- metrics/heapster.go
Signed-off-by: allencloud <allen.sun@daocloud.io>
I found that in heapster flag validation there is incorrect issue. When I input a value of 5s, it will show the no error, while with a value less than 5s, it shows `metric resolution needs to be greater than 5 seconds`.
And I think the error does not take 5s into consideration, ad we need to update this line of log.
What this PR did:
1. fix incorrect expression in heapster flag validation log
> fix incorrect expression in heapster flag validation log

- metrics/sources/kubelet/kubelet.go
What I did:
1. remove unused viriables in kubelet.go, since nodeNames is never used in code.
Signed-off-by: allencloud <allen.sun@daocloud.io>
> remove unused viriables in kubelet.go

- deploy/kube-config/influxdb/grafana.yaml
- deploy/kube-config/influxdb/heapster.yaml
- deploy/kube-config/influxdb/influxdb.yaml
- grafana/Makefile
- grafana/run.sh
- influxdb/Makefile
- influxdb/config.toml
Rebased version of https://github.com/kubernetes/heapster/pull/1700 to have recent inflxudb asap
Original description:
```
Updates grafana to v4.3.2 and influxdb to v1.3.0
fixes #1698 as a consequence
```
Updates grafana 4.4.3 and influxdb to v1.3.3
> Rebased #1700: Fix grafana

- metrics/sources/kubelet/kubelet.go
- metrics/sources/kubelet/kubelet_test.go
- metrics/sources/summary/summary.go
Support nodes that look like:
```
status:
addresses:
- address: 10.0.0.1
type: ExternalIP
- address: kubernetes-node-1
type: Hostname
```
> Support NodeExternalIP

- common/honeycomb/dummy_honeycomb.go
- common/honeycomb/honeycomb.go
- common/honeycomb/honeycomb_test.go
- docs/sink-configuration.md
- docs/sink-owners.md
- events/sinks/factory.go
- events/sinks/honeycomb/driver.go
- events/sinks/honeycomb/honeycomb_test.go
- metrics/sinks/factory.go
- metrics/sinks/honeycomb/driver.go
- metrics/sinks/honeycomb/honeycomb_test.go
Honeycomb is a logging service that aggregates logs from multiple sources. This PR introduces a new heapster sink that allows Honeycomb users to access heapster metrics.
> Add Honeycomb Sink for Heaptser

- docs/storage-schema.md
- metrics/heapster.go
- metrics/options/options.go
- metrics/processors/node_autoscaling_enricher.go
- metrics/processors/pod_based_enricher.go
- metrics/processors/pod_based_enricher_test.go
- metrics/util/label_copier.go
- metrics/util/label_copier_test.go
- metrics/util/util.go
This PR resolves #807.
There are two new options:
- `--store-label` stores label as separate label/tag in addition to concatenated one
- `--ignore-label` allows to prevent label from being used in concatenation
Custom tags allow for more efficient data retrieval from InfluxDB. Ignoring labels reduces redundancy.
Using both options in order allows for seamless transition from old (regexp based) to new (exact match) retrievals.
> Storing and/or ignoring user-provided labels

- metrics/core/types.go
- metrics/manager/manager.go
- metrics/sources/kubelet/kubelet.go
- metrics/sources/kubelet/kubelet_test.go
- metrics/sources/manager.go
- metrics/sources/manager_test.go
- metrics/sources/summary/summary.go
- metrics/sources/summary/summary_test.go
- metrics/util/dummies.go
When error in scraping a knode metrics, heapster should fail fast after error checking.
Currently, even when scraping error, an successful scrape log will also emitted which is confusing.
/cc @DirectXMan12 @piosz
> fast return when scrape error

- common/kafka/kafka.go
- docs/sink-configuration.md
Currently kafka sends events and metrics uncompressed, which causes huge sizes.
> Add gzip compression for kafka sinks

- metrics/heapster.go
- metrics/sources/kubelet/kubelet.go
- metrics/sources/kubelet/kubelet_client.go
- metrics/sources/kubelet/kubelet_test.go
- metrics/sources/summary/summary.go
- metrics/sources/summary/summary_test.go
This PR tries to solve problems seen in #1852, handling addresses indiferently if the are IPv4 or IPv6. For that it uses `net.IP` type and `net.JoinHostPort` function.
It also makes public the function `kubelet.GetHostnameAndIP` used to obtain hostname and ip of a node so this code can be reused.
> Handle IPs as net.IP objects in the way to support IPv6

- metrics/sources/summary/summary.go
iNode metrics, specifically `filesystem/inodes` and `filesystem/inodes_free` were not getting scraped in the summary source. Added code to do so.
> Adds scraping iNode metrics in summary api

- metrics/core/metrics.go
**Problem**
metric `filesystem/available` was not showing up on the sink side
**Solution**
Implemented `HasLabeledMetric` and `GetLabeledMetric` by adapting the same methods of the `filesystem/limit` metric
**Testing**
Tested in our monitoring setup and now getting the desired `filesystem/available` metric at our sink
> Adds (fixes) filesystem/available metric

- metrics/sinks/wavefront/wavefront.go
Blank tag values are not valid in Wavefront data format and fail the data point entirely, so we need to filter them out before sending
> Wavefront sink: filter out tags with blank values

- metrics/heapster.go
- metrics/options/options.go
- metrics/sinks/manager.go
The sink export data timeout was set to 20 seconds with no way to
configure it.
Add a flag which lets users specify the value for the sink export data
timeout.
> Make the sink export data timeout configurable

- metrics/sinks/influxdb/influxdb.go
This PR will fix removing of blacklist labels for labeled metrics for InfluxDB. Currently, we do not remove blacklist labels for all labels of a labeled metric.
/cc @DirectXMan12 @piosz @loburm
> fix remove blacklist labels for influxdb

- Godeps/Godeps.json
- metrics/sinks/hawkular/client.go
- metrics/sinks/hawkular/driver.go
- metrics/sinks/hawkular/driver_test.go
- metrics/sinks/hawkular/types.go
- vendor/github.com/hawkular/hawkular-client-go/metrics/client.go
* Don't store structs in the memory, instead calculate a hash value which is used for compare
* Always compare the current cached value to the one Heapster provides to see instant change in labels
* Reduce the amount of goroutines for most cache lookups
* Expire the cache items if the Heapster has not seen the metric in two scrapes
* Improve startup time by loading definitions from a new endpoint designed for Openshift (disable with disablePreCaching setup)
With large amount of metrics, this should reduce the amount of memory used by the sink (with 20000 pods, Heapster memory usage was reduced from 5.7GB to 3.9GB)
@DirectXMan12 This replaces the previous PR. These changes have been tested against Heapster 1.3.0, so this is a rebase for newer Heapster.
> Hawkular, reduce the sink's memory usage in definition caching

- events/sinks/factory.go
- metrics/sinks/factory.go
* Fix nil pointer dereference when a metric sink return an error (use uri to get sink info vs .Name() on a nil pointer)
* Harmonize metrics and events factory code
> Fix nil pointer dereference when a sink return (nil, err)

- OWNERS
- events/sinks/elasticsearch/OWNERS
- events/sinks/gcl/OWNERS
- events/sinks/honeycomb/OWNERS
- events/sinks/influxdb/OWNERS
- events/sinks/kafka/OWNERS
- events/sinks/riemann/OWNERS
- metrics/sinks/elasticsearch/OWNERS
- metrics/sinks/gcm/OWNERS
- metrics/sinks/graphite/OWNERS
- metrics/sinks/hawkular/OWNERS
- metrics/sinks/honeycomb/OWNERS
- metrics/sinks/influxdb/OWNERS
- metrics/sinks/kafka/OWNERS
- metrics/sinks/librato/OWNERS
- metrics/sinks/opentsdb/OWNERS
- metrics/sinks/riemann/OWNERS
- metrics/sinks/stackdriver/OWNERS
- metrics/sinks/statsd/OWNERS
- metrics/sinks/wavefront/OWNERS
Each sink has its own OWNERS file, which should make triage and merging
easier once we turn the bot on.
> Add OWNERS files

- grafana/OWNERS
This adds the Influx owners to the Grafana directory, so that people
knowlegable about Influx can also approve the Influx Grafana templates.
> [infra] Add Influx owners to the Grafana directory
